### ISSUE TITLE
efiperun

### ISSUE THREAD

**Issue by mustangV** [jethrogb/uefireverse#2]
Hello. I want to use yours a miracle the tool. I download the GNU EFI package and wrote its way to the Makefile. Farther I build  jemalloc 3.6.0 in a subdirectory. But in case of build "efiperun" there is an error: 
collect2: error: ld returned 1 exit status 
Makefile:16: recipe for tarrget efiperun failed 
make: **\* [efiperun] Error 1

**Comment by jethrogb** [comment]
Please post the entire error message.

**Comment by mustangV** [comment]
uubuntu@ubuntu:~/Desktop/uefi/uefireverse-master/efiperun$ make
g++  stubs.o peloader.o efiperun.o efihooks.o debugmodule_example.o vast/filesystem.o jemalloc_custom.a -lpthread -o efiperun
/usr/bin/ld: i386 architecture of input file `stubs.o' is incompatible with i386:x86-64 output
/usr/bin/ld: i386 architecture of input file`peloader.o' is incompatible with i386:x86-64 output
/usr/bin/ld: i386 architecture of input file `efiperun.o' is incompatible with i386:x86-64 output
stubs.o: In function`GetVariable(unsigned short_, EFI_GUID_, unsigned int_, unsigned long long_, void_)':
/home/inux/Desktop/setup/uefireverse-master/efiperun/stubs.cpp:200: undefined reference to `get_variable(EFI_GUID_, unsigned short_, unsigned long long_, unsigned int_)'
stubs.o: In function `__gnu_cxx::new_allocator<int>::allocate(unsigned int, void const_)':
/usr/include/c++/4.9/ext/new_allocator.h:104: undefined reference to `operator new(unsigned int)'
stubs.o: In function`__gnu_cxx::new_allocator<void*>::allocate(unsigned int, void const_)':
/usr/include/c++/4.9/ext/new_allocator.h:104: undefined reference to `operator new(unsigned int)'
efiperun.o: In function`__gnu_cxx::new_allocator<void (_)()>::allocate(unsigned int, void const_)':
/usr/include/c++/4.9/ext/new_allocator.h:104: undefined reference to `operator new(unsigned int)'
efiperun.o: In function`__gnu_cxx::new_allocator<std::_Rb_tree_node<std::pair<int const, std::pair<int, std::string> > > >::allocate(unsigned int, void const_)':
/usr/include/c++/4.9/ext/new_allocator.h:104: undefined reference to `operator new(unsigned int)'
efiperun.o: In function`__gnu_cxx::new_allocator<std::_Rb_tree_node<std::pair<int const, std::pair<int, std::pair<loadinfo, std::string> > > > >::allocate(unsigned int, void const_)':
/usr/include/c++/4.9/ext/new_allocator.h:104: undefined reference to `operator new(unsigned int)'
efihooks.o: In function`efi_hooks_init()':
/home/uubuntu/Desktop/uefi/uefireverse-master/efiperun/efihooks.cpp:359: undefined reference to `GetVariable(unsigned short_, EFI_GUID_, unsigned int_, unsigned long_, void_)'
/home/uubuntu/Desktop/uefi/uefireverse-master/efiperun/efihooks.cpp:361: undefined reference to `SetVariable(unsigned short*, EFI_GUID*, unsigned int, unsigned long, void*)'
/home/uubuntu/Desktop/uefi/uefireverse-master/efiperun/efihooks.cpp:366: undefined reference to`AllocatePages(EFI_ALLOCATE_TYPE, EFI_MEMORY_TYPE, unsigned long, unsigned long_)'
/home/uubuntu/Desktop/uefi/uefireverse-master/efiperun/efihooks.cpp:369: undefined reference to `AllocatePool(EFI_MEMORY_TYPE, unsigned long, void__)'
/home/uubuntu/Desktop/uefi/uefireverse-master/efiperun/efihooks.cpp:391: undefined reference to `GetNextMonotonicCount(unsigned long_)'
/home/uubuntu/Desktop/uefi/uefireverse-master/efiperun/efihooks.cpp:400: undefined reference to `LocateHandleBuffer(EFI_LOCATE_SEARCH_TYPE, EFI_GUID*, void*, unsigned long*, void***)'
/home/uubuntu/Desktop/uefi/uefireverse-master/efiperun/efihooks.cpp:405: undefined reference to`CopyMem(void_, void_, unsigned long)'
/home/uubuntu/Desktop/uefi/uefireverse-master/efiperun/efihooks.cpp:406: undefined reference to `SetMem(void*, unsigned long, unsigned char)'
/home/uubuntu/Desktop/uefi/uefireverse-master/efiperun/efihooks.cpp:414: undefined reference to`QueryMode(_SIMPLE_TEXT_OUTPUT_INTERFACE_, unsigned long, unsigned long_, unsigned long_)'
/home/uubuntu/Desktop/uefi/uefireverse-master/efiperun/efihooks.cpp:423: undefined reference to `QueryMode(_SIMPLE_TEXT_OUTPUT_INTERFACE_, unsigned long, unsigned long_, unsigned long_)'
/home/uubuntu/Desktop/uefi/uefireverse-master/efiperun/efihooks.cpp:477: undefined reference to `GetAcpiTable(void*, long, void**, unsigned int*, unsigned long*)'
/home/uubuntu/Desktop/uefi/uefireverse-master/efiperun/efihooks.cpp:478: undefined reference to`SetAcpiTable(void_, void_, unsigned char, unsigned int, unsigned long_)'
collect2: error: ld returned 1 exit status
Makefile:16: recipe for target 'efiperun' failed
make: *_\* [efiperun] Error 1

**Comment by jethrogb** [comment]
These worry me:

```
/usr/bin/ld: i386 architecture of input file `stubs.o' is incompatible with i386:x86-64 output
/usr/bin/ld: i386 architecture of input file `peloader.o' is incompatible with i386:x86-64 output
/usr/bin/ld: i386 architecture of input file `efiperun.o' is incompatible with i386:x86-64 output
```

Are you compiling on a 32-bit machine? Can you post the output of `make clean all`?

**Comment by mustangV** [comment]
uubuntu@ubuntu:~/Desktop/uefi/uefireverse-master/efiperun$ uname -a
Linux ubuntu 3.16.0-23-generic #31-Ubuntu SMP Tue Oct 21 17:56:17 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by mustangV** [comment]
uubuntu@ubuntu:~/Desktop/uefi/uefireverse-master/efiperun$ make clean all
rm -f stubs.o peloader.o efiperun.o efihooks.o debugmodule_example.o vast/filesystem.o jemalloc_custom.a efiperun
g++ -I/home/uubuntu/Desktop/uefi/gnu-efi-3.0.3/inc -I/home/uubuntu/Desktop/uefi/gnu-efi-3.0.3/inc/x86_64 -I. -DGNU_EFI_USE_MS_ABI -g -std=c++11 -c stubs.cpp -o stubs.o
gcc -I/home/uubuntu/Desktop/uefi/gnu-efi-3.0.3/inc -I/home/uubuntu/Desktop/uefi/gnu-efi-3.0.3/inc/x86_64 -I. -DGNU_EFI_USE_MS_ABI -g -std=gnu99 -c peloader.c -o peloader.o
g++ -I/home/uubuntu/Desktop/uefi/gnu-efi-3.0.3/inc -I/home/uubuntu/Desktop/uefi/gnu-efi-3.0.3/inc/x86_64 -I. -DGNU_EFI_USE_MS_ABI -g -std=c++11 -c efiperun.cpp -o efiperun.o
g++ -I/home/uubuntu/Desktop/uefi/gnu-efi-3.0.3/inc -I/home/uubuntu/Desktop/uefi/gnu-efi-3.0.3/inc/x86_64 -I. -DGNU_EFI_USE_MS_ABI -g -std=c++11 -c efihooks.cpp -o efihooks.o
g++ -I/home/uubuntu/Desktop/uefi/gnu-efi-3.0.3/inc -I/home/uubuntu/Desktop/uefi/gnu-efi-3.0.3/inc/x86_64 -I. -DGNU_EFI_USE_MS_ABI -g -std=c++11 -c debugmodule_example.cpp -o debugmodule_example.o
g++ -I/home/uubuntu/Desktop/uefi/gnu-efi-3.0.3/inc -I/home/uubuntu/Desktop/uefi/gnu-efi-3.0.3/inc/x86_64 -I. -DGNU_EFI_USE_MS_ABI -g -std=c++11 -c vast/filesystem.cpp -o vast/filesystem.o
objcopy --redefine-sym mmap=wrapped_mmap jemalloc-3.6.0/lib/libjemalloc_pic.a jemalloc_custom.a 
g++  stubs.o peloader.o efiperun.o efihooks.o debugmodule_example.o vast/filesystem.o jemalloc_custom.a -lpthread -o efiperun

**Comment by jethrogb** [comment]
It works, then?

**Comment by mustangV** [comment]
Yes, "make clean all" works.

**Comment by mustangV** [comment]
Further "make install"?

**Comment by jethrogb** [comment]
No, just run.

**Comment by mustangV** [comment]
Thanks.
