### ISSUE TITLE
Troubleshooting segfaults

### ISSUE THREAD

**Issue by ghost** [jethrogb/uefireverse#4]
I'm not sure where to start and I'm a bit out of my depth here.
LenovoBT.efi crashes (!) on real hardware anyway.

```
voltagex@devbox:~/src/uefireverse/efiperun$ ./efiperun --unsafe /media/recovery/EFI/Boot/LenovoBT.EFI 
PE mmap: start=00007f135abf7000, end=00007f135aff6fff
PE mmap: start=00007f135a7f8000, end=00007f135aff6fff
  new dummy @address 0000000000e76430
Intialization done. Loading images.
PE mmap: start=00007f135be74000, end=00007f135bf2efff
Segmentation fault
```

Can provide a sample in 8+ hours.

**Comment by jethrogb** [comment]
This is not really an efiperun issue: you're running some unknown code with unknown dependencies and unknown inputs, so segfaults are very likely. Compare to loading a shared module and just randomly calling functions with no known signature.

You'll need to figure out what the module is trying to do and how to make that work. You can do this for example by running in gdb and looking at the disassembly.
