### ISSUE TITLE
Getting Backtrace with tianocore/Shell.efi

### ISSUE THREAD

**Issue by daedalus** [jethrogb/uefireverse#7]
Hi,

I'm trying wth the shell from the tianocore project and I get a backtrace:

wget https://github.com/tianocore/edk2/raw/master/EdkShellBinPkg/MinimumShell/X64/Shell.efi

code/uefireverse/efiperun/efiperun --unsafe  Shell.efi 
PE mmap: start=00007f0ed1d94000, end=00007f0ed2193fff
PE mmap: start=00007f0ed1995000, end=00007f0ed2193fff
  new dummy @address 0000555a04039c40
Intialization done. Loading images.
PE mmap: start=00007f0ed31d0000, end=00007f0ed3228fff
Loaded MAIN_PE_IMAGE at 0x7f0ed31d0000
Request Protocol GUID:EFI_LOADED_IMAGE_PROTOCOL
LocateHandleBuffer Protocol GUID:EFI_UNICODE_COLLATION2_PROTOCOL
LocateHandleBuffer Protocol GUID:EFI_UNICODE_COLLATION_PROTOCOL
PE mmap: start=00007f0ed1800000, end=00007f0ed1bfffff
AllocatePool
  @address 00007f0ed180e1c0, size=190
Called g_efi_system_table_BootServices::LocateHandle
Aborted. Backtrace:
  ( 0) 0x0000555a03c375c8 code/uefireverse/efiperun/efiperun(+0x235c8) [0x555a03c375c8]
  ( 1) 0x0000555a03c3779b code/uefireverse/efiperun/efiperun(+0x2379b) [0x555a03c3779b]
  ( 2) 0x0000555a03c3fb00 code/uefireverse/efiperun/efiperun(+0x2bb00) [0x555a03c3fb00]
  ( 3) MAIN_PE_IMAGE::IMAGE_BASE+0x0002c81c [0x7f0ed31fc81c]

**Comment by jethrogb** [comment]
@daedalus efiperun is currently just a bare framework to load and run modules, it intentionally doesn't implement everything. It is intended that users will need to do some work to make it work for their own modules. I unfortunately don't have time to help users debug their individual issues but will gladly review any code contributions that make the framework better!

**Comment by daedalus** [comment]
Oh, thanks for the explanation.
I'm closing this ticket.
Keep up with this good project.
